from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from .config import configure_logging
from .evidence_builder import EvidenceBuilder

logger = logging.getLogger(__name__)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="JAW evidence build CLI")
    parser.add_argument("--input", required=True, type=Path, help="Extraction JSON file generated by jaw-ingest.")
    parser.add_argument("--output", required=True, type=Path, help="Output directory for canonical evidence JSONL files.")
    parser.add_argument("--cache-dir", type=Path, default=Path(".cache"), help="Cache directory for evidence build state.")
    parser.add_argument("--force", action="store_true", help="Force rebuild of all evidence and facts.")
    parser.add_argument("--no-cache", action="store_true", help="Disable incremental cache/state usage.")
    parser.add_argument(
        "--document-index",
        type=Path,
        default=None,
        help="Optional document_index.csv (doc_id,doc_type,filename,size_bytes) providing each document's "
        "semantic type (e.g. reference_letter, completion_certificate) - stored in DocumentRecord.metadata "
        "and used as context for semantic extraction. Skipped if not provided or the file doesn't exist.",
    )
    parser.add_argument("--log-level", default="INFO", help="Logging level.")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    configure_logging(args.log_level)
    builder = EvidenceBuilder(
        input_path=args.input,
        output_dir=args.output,
        cache_dir=args.cache_dir,
        force=args.force,
        no_cache=args.no_cache,
        document_index_path=args.document_index,
    )

    report = builder.build()
    logger.info("Evidence build complete. Documents: %d, evidence: %d, facts: %d", report.documents_processed, report.evidence_created, report.facts_created)
    print(json.dumps(report.model_dump(mode="json"), indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
