#!/usr/bin/env python3
"""
build_doc_map.py — one human-readable catalogue of the whole corpus.

Reads an evidence root (documents.jsonl, evidence.jsonl, facts.jsonl) and writes DOC_MAP.md:
one line per document saying what it is and the salient facts pulled from it. Purely
deterministic — no LLM, no network. It is a debugging aid, not part of the query path: when
an answer looks wrong you open this and see, at a glance, what the system believes each
document contains and where a number came from.

    python scripts/build_doc_map.py --evidence-root data/evidence
    python scripts/build_doc_map.py --evidence-root data/evidence_full --out DOC_MAP.md

The map is grouped by the corpus's own document type (hackathon_doc_type from
document_index.csv, if it was ingested), with a per-type count header, then per document:

    - DOC-CC-001  ·  RCC Bridge — Gujarat Pkg-1  ·  3 pages
        contract_value: 333800000   date: 2011-02-06

The "title" hint is the most identifying early text block (the one naming a package /
project), so a certificate reads as its work name rather than its opaque id. Facts shown are
the normalized, validated ones — the same values the query engine computes over — so if a
number is wrong here it is wrong at the source, before any reasoning.
"""
import argparse, collections, json, re
from pathlib import Path

MONEY_PREDS = {"contract_value", "amount", "monetary_value", "rate"}
TITLE_HINT = re.compile(r"(Pkg-\d+|—)")  # a work title names a package or uses an em-dash


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def fmt_money(v) -> str:
    try:
        return f"{int(float(v)):,}"
    except (TypeError, ValueError):
        return str(v)


def title_hint(blocks: list[str]) -> str:
    """The most identifying early block: prefer one naming a package, else the first
    substantive line, trimmed."""
    candidates = [b for b in blocks[:8] if b and len(b.strip()) > 4]
    named = [b for b in candidates if TITLE_HINT.search(b)]
    pick = (named or candidates or [""])[0]
    pick = re.sub(r"\s+", " ", pick).strip()
    # drop a leading label like "Name of Work " if present
    pick = re.sub(r"^(Name of Work|Project Name|Work|Project)\s+", "", pick, flags=re.IGNORECASE)
    return pick[:70]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--evidence-root", type=Path, default=Path("data/evidence"))
    ap.add_argument("--out", type=Path, default=None, help="default: <evidence-root>/DOC_MAP.md")
    args = ap.parse_args()

    root = args.evidence_root
    docs = load_jsonl(root / "documents.jsonl")
    evidence = load_jsonl(root / "evidence.jsonl")
    facts = load_jsonl(root / "facts.jsonl")
    if not docs:
        raise SystemExit(f"no documents.jsonl under {root} — run the evidence builder first")

    # text blocks per document (for the title hint), in page/block order
    blocks_by_doc: dict[str, list[str]] = collections.defaultdict(list)
    for e in evidence:
        if e.get("source_type") == "pdf":
            blocks_by_doc[e["document_id"]].append(str(e.get("content", {}).get("text") or ""))

    # validated facts per document
    facts_by_doc: dict[str, list[dict]] = collections.defaultdict(list)
    for f in facts:
        if f.get("validation_status") == "valid":
            facts_by_doc[f["document_id"]].append(f)

    def doc_type(rec: dict) -> str:
        return (rec.get("metadata") or {}).get("hackathon_doc_type") or rec.get("document_type") or "unknown"

    by_type: dict[str, list[dict]] = collections.defaultdict(list)
    for rec in docs:
        by_type[doc_type(rec)].append(rec)

    lines = ["# Document map", "",
             f"`{len(docs)}` documents · `{len(evidence)}` evidence fragments · "
             f"`{len(facts)}` facts. Generated by `scripts/build_doc_map.py` — deterministic, no LLM.", ""]
    lines.append("| document type | count |")
    lines.append("|---|---:|")
    for t in sorted(by_type, key=lambda k: -len(by_type[k])):
        lines.append(f"| {t} | {len(by_type[t])} |")
    lines.append("")

    for t in sorted(by_type, key=lambda k: -len(by_type[k])):
        lines.append(f"## {t}  ({len(by_type[t])})")
        lines.append("")
        for rec in sorted(by_type[t], key=lambda r: r["document_id"]):
            did = rec["document_id"]
            size = (f"{rec['page_count']} pages" if rec.get("page_count")
                    else f"{rec['sheet_count']} sheets" if rec.get("sheet_count") else "")
            hint = title_hint(blocks_by_doc.get(did, []))
            head = f"- **{did}**"
            if hint:
                head += f"  ·  {hint}"
            if size:
                head += f"  ·  {size}"
            lines.append(head)

            # salient facts: money first, then dates, then a couple of other predicates,
            # deduped by (predicate, value)
            seen, money_bits, date_bits, other_bits = set(), [], [], []
            for f in facts_by_doc.get(did, []):
                pred, nv = f.get("predicate", ""), f.get("normalized_value")
                if nv in (None, ""):
                    continue
                key = (pred, str(nv))
                if key in seen:
                    continue
                seen.add(key)
                if pred in MONEY_PREDS and f.get("normalized_type") in ("currency_inr", "number"):
                    money_bits.append(f"{pred}: {fmt_money(nv)}")
                elif f.get("normalized_type") == "date":
                    date_bits.append(f"{pred}: {nv}")
                elif pred not in ("description", "item_number", "unit", "quantity"):
                    other_bits.append(f"{pred}: {nv}")
            detail = "   ".join(money_bits[:4] + date_bits[:3] + other_bits[:3])
            if detail:
                lines.append(f"    {detail}")
        lines.append("")

    out = args.out or (root / "DOC_MAP.md")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}  ({len(docs)} documents, {sum(len(v) for v in by_type.values())} rows)")


if __name__ == "__main__":
    main()
